[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "cors", "apn", "node-pushnotifications"]
  included_files = ["netlify/functions/api/cert/*.pem", "netlify/functions/api/api.ts"]

[experimental]
  kv = true